In [1]:
## Importing Image

from PIL import Image
import numpy as np

img=Image.open('dogs.jpeg')
np_img = np.array(img)
np_img

array([[[240, 240, 240],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       [[240, 240, 240],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       [[240, 240, 240],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]],

       ...,

       [[252, 248, 249],
        [254, 250, 251],
        [255, 253, 254],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[247, 245, 246],
        [250, 248, 249],
        [255, 253, 254],
        ...,
        [255, 255, 255],
        [252, 252, 252],
        [244, 244, 244]],

       [[253, 251, 254],
        [253, 251, 254],
        [253, 251, 252],
        ...,
        [254, 254, 254],
        [254, 254, 254],
        [254, 254, 254]]

In [2]:
np_img.ndim

3

In [3]:
np_img.shape

(185, 272, 3)

In [4]:
newarr=np_img.reshape(185,272*3)

In [5]:
newarr.shape

(185, 816)

In [6]:
## KMeans Clustering
########################
from sklearn.cluster import KMeans

km=KMeans(n_clusters=3)
km.fit(newarr)

KMeans(n_clusters=3)

In [7]:
km.labels_

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2], dtype=int32)

In [8]:
import pandas as pd

In [9]:
df=pd.DataFrame(newarr)

In [10]:
df['label']=km.labels_

In [11]:
df.head()

0    1    2    3    4    5    6    7    8    9  ...  807  808  809  810  \
0  240  240  240  255  255  255  255  255  255  251  ...  254  254  254  254   
1  240  240  240  255  255  255  255  255  255  251  ...  254  254  254  254   
2  240  240  240  255  255  255  255  255  255  251  ...  254  254  254  254   
3  240  240  240  255  255  255  255  255  255  251  ...  254  254  254  254   
4  240  240  240  255  255  255  255  255  255  251  ...  254  254  254  254   

   811  812  813  814  815  label  
0  254  254  254  254  254      2  
1  254  254  254  254  254      2  
2  254  254  254  254  254      2  
3  254  254  254  254  254      2  
4  254  254  254  254  254      2  

[5 rows x 817 columns]

In [12]:
la=df.iloc[0][:-1]

In [14]:
n=np.array(la)

In [19]:
n.reshape(1,-1).shape

(1, 816)

In [61]:
# np.array(la).reshape(1,-1).shape

(1, 816)

In [20]:
y_pred=km.predict(np.array(la).reshape(1,-1))

In [21]:
y_pred

array([2], dtype=int32)